name: rlgame-ppo
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  - scipy
  - matplotlib
  - tqdm
  - gymnasium
  - pytorch::pytorch
  - nvidia::pytorch-cuda=12.4
